FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia el resto del codigo fuente
COPY . .

# Expone el puerto por defecto de Nest
EXPOSE 3000

CMD ["npm", "run", "start:dev"]
